<div>
    <div class="row-fluid">
        <div class="span12">
            <h2><?php echo $this->evento->nome; ?> - <?php echo date("d/m/Y", strtotime($this->evento->realizacao)); ?></h2>
        </div>
    </div>

    <hr>
    <div class="row-fluid">

        <?php include(APPLICATION_PATH . '/views/scripts/partials/menu-evento.phtml'); ?>

        <div class="span9">
            <div class="row-fluid">
                <div class="span6 well">
                    <h4>Inscrições</h4>
                    <hr/>
                    <p><strong>Confirmadas</strong> - <span class="badge-success badge">200</span></p>
                    <p><strong>Não Confirmadas</strong> - <span class="badge-warning badge">100</span></p>
                    <p><strong>Disponíveis</strong> - <span class="badge-important badge">200</span></p>
                </div>

                <div class="span6 well">
                    <h4>Balanço Financeiro</h4>
                    <hr/>

                    <p><strong>Total de Receitas</strong> - <span class="badge-success badge">R$ 1.000,00</span></p>
                    <p><strong>Total de Despesas</strong> - <span class="badge-important badge">R$ 500,00</span></p>
                    <p><strong>Saldo</strong> - <span class="badge-success badge">R$ 500,00</span></p>
                </div>
            </div>
        </div>
    </div>
</div>