<div class="row-fluid">
    <div class="span12">
        <h2><i class="icon-time"></i> Eventos</h2>

        <hr>

        <p><a href="/eventos/novo" class="btn btn-primary"><i class="icon-user"></i> &nbsp; Novo Evento</a></p>

        <table class="table table-hover dataTable">
            <thead>
                <tr>
                    <th width="5%">#id</th>
                    <th>Nome</th>
                    <th class="txtCenter">Realização</th>
                    <th class="txtCenter">Máximo inscrições</th>
                    <th class="txtCenter">Valor</th>
                    <th width="10%" class="txtCenter">Situação</th>
                    <th width="15%">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->eventos as $evento) : ?>
                    <tr>
                        <td><?php echo $evento->id; ?></td>
                        <td><a href="/eventos/editar/id/<?php echo $evento->id; ?>"><?php echo $evento->nome; ?></a></td>
                        <td><?php echo date("d/m/Y", strtotime($evento->realizacao)); ?></td>
                        <td class="txtCenter"><?php echo $evento->maximoInscricoes; ?></td>
                        <td class="txtCenter">R$ <?php echo number_format($evento->valor, 2, ',', '.'); ?></td>
                        <td class="txtCenter"><?php echo $evento->situacao ?></td>
                        <td>
                            <a href="/eventos/editar/id/<?php echo $evento->id; ?>" class="btn btn-small"><i class="icon-edit" title="Editar Evento"></i></a>
                            <a href="/eventos/remover/id/<?php echo $evento->id; ?>" class="btn btn-danger btn-small delete" title="Cancelar Evento"><i class="icon-remove-sign"></i></a>
                            <a href="/eventos/detalhes/id/<?php echo $evento->id; ?>" class="btn btn-info btn-small" title="Gerenciar Evento"><i class="icon-gears"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">
            $(function() {
                var oTable = $('.dataTable').dataTable({
                    "sPaginationType": "full_numbers",
                    "sDom": 'f<"toolbar">lrtip',
                    "oLanguage": {
                        "sProcessing": "Processando...",
                        "sLengthMenu": "Mostrar _MENU_ registros",
                        "sZeroRecords": "Não foram encontrados resultados",
                        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
                        "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                        "sInfoPostFix": "",
                        "sSearch": "Buscar:",
                        "sUrl": "",
                        "oPaginate": {
                            "sFirst": "Primeiro",
                            "sPrevious": "Anterior",
                            "sNext": "Seguinte",
                            "sLast": "Último"
                        }
                    }
                });
                var select = '<select name="situacao">';
                select += '<option value="">Todos</option>';
                select += '<option value="Sim">Ativos</option>';
                select += '<option value="Não">Inativos</option>';
                select += '</select>';
                $("div.toolbar").html('<label>Filtrar: ' + select + '</label>');
                $('select[name=situacao]', this).change(function() {
                    oTable.fnFilter($(this).val(), 4);
                });
            });
        </script> 
    </div>
</div>