<div>
    <div class="row-fluid">
        <div class="span12">
            <h2><?php echo $this->evento->nome; ?> - <?php echo date("d/m/Y", strtotime($this->evento->realizacao)); ?></h2>
        </div>
    </div>

    <hr>

    <ul class="breadcrumb">
        <li><a href="/">Visão Geral</a> <span class="divider">/</span></li>
        <li><a href="/eventos">Eventos</a> <span class="divider">/</span></li>
        <li><a href="/eventos/detalhes/id/<?php echo $this->evento->id; ?>"><?php echo $this->evento->nome; ?></a> <span class="divider">/</span></li>
        <li class="active">Despesas</li>
    </ul>

    <div class="row-fluid">

        <?php include(APPLICATION_PATH . '/views/scripts/partials/menu-evento.phtml'); ?>

        <div class="span9">
            <p><a href="/lancamentos/novo/evento/<?php echo $this->evento->id; ?>" class="btn btn-primary"><i class="icon-resize-full"></i> &nbsp; Nova Despesa</a></p>

            <table class="table table-hover dataTable">
                <thead>
                    <tr>
                        <th width="5%">#id</th>
                        <th>Descricao</th>
                        <th>Vencimento</th>
                        <th>Valor</th>
                        <th>Situação</th>
                        <th width="17%">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->lancamentos as $lancamento) : ?>
                        <tr>
                            <td><?php echo $lancamento->id; ?></td>
                            <td><?php echo $lancamento->descricao; ?></td>
                            <td><?php echo date("d/m/Y",strtotime($lancamento->dataVencimento)); ?></td>
                            <td><?php echo Zend_Registry::get('currency')->toCurrency($lancamento->valor); ?></td>
                            <td>
                                <?php echo ($lancamento->situacao == 0 ? '<span class="badge badge-important">Pendente</span>' : '<span class="badge badge-success">Pago</span>'); ?>
                            </td>
                            <td>
                                <?php if ($lancamento->situacao == 0): ?>
                                    <a href="/lancamentos/baixar/id/<?php echo $lancamento->id; ?>/evento/<?php echo $this->evento->id; ?>" class="btn btn-small btn-success" data-toggle="tooltip" title="Baixar Lançamento"><i class="icon-arrow-down"></i></a>
                                <?php endif; ?>

                                <?php if ($lancamento->situacao == 1): ?>
                                    <a href="/lancamentos/estornar/id/<?php echo $lancamento->id; ?>/evento/<?php echo $this->evento->id; ?>" class="btn btn-small btn-danger"><i class="icon-arrow-up" title="Estornar Pagamento"></i></a>
                                <?php endif; ?>

                                <?php if ($lancamento->situacao == 0): ?>
                                    <a href="/lancamento/editar/id/<?php echo $lancamento->id; ?>/evento/<?php echo $this->evento->id; ?>" class="btn btn-small"><i class="icon-edit" title="Editar Lançamento"></i></a>
                                    <a href="/lancamento/remover/id/<?php echo $lancamento->id; ?>/evento/<?php echo $this->evento->id; ?>" class="btn btn-danger btn-small delete" title="Remover Lançamento"><i class="icon-remove-sign"></i></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <script type="text/javascript">
                $(function() {
                    var oTable = $('.dataTable').dataTable({
                        "sPaginationType": "full_numbers",
                        "sDom": 'f<"toolbar">lrtip',
                        "oLanguage": {
                            "sProcessing": "Processando...",
                            "sLengthMenu": "Mostrar _MENU_ registros",
                            "sZeroRecords": "Não foram encontrados resultados",
                            "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                            "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
                            "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                            "sInfoPostFix": "",
                            "sSearch": "Buscar:",
                            "sUrl": "",
                            "oPaginate": {
                                "sFirst": "Primeiro",
                                "sPrevious": "Anterior",
                                "sNext": "Seguinte",
                                "sLast": "Último"
                            }
                        }
                    });
                });
            </script> 
        </div>
    </div>
</div>