<div class="row-fluid">
    <h2>Novo Usuário</h2>

    <hr>

    <form method="post" class="form-horizontal" id="usuario">
        <div class="row-fluid">
            <div class="span1 txtCenter">
                <i class="icon-user icon-3x muted"></i>
            </div>
            <div class="span11">
                <div class="control-group">
                    <label class="control-label">
                        <label for="nome">Nome</label>
                    </label>
                    <div class="controls">
                        <input type="text" name="nome" class="input-xlarge">							
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">
                        <label for="email">E-mail</label>
                    </label>
                    <div class="controls">
                        <input type="text" name="email" class="input-xlarge">							
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">
                        <label for="senha">Senha</label>
                    </label>
                    <div class="controls">
                        <input type="password" name="senha" id="senha" class="input-xlarge">							
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">
                        <label for="confirma">Confirma senha</label>
                    </label>
                    <div class="controls">
                        <input type="password" name="confirma" class="input-xlarge">							
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">
                        <label for="role">Role</label>
                    </label>
                    <div class="controls">
                        <select name="role" class="input-xlarge">
                            <option value="">Selecione um role....</option> 
                            <option value="usuario">Usuário</option> 
                            <option value="admin">Administrador</option> 
                        </select>							
                    </div>
                </div>
            </div>
        </div>

        <div class="form-actions">
            <input type="submit" id="submitbutton" class="btn btn-primary" value="Salvar">  
            <a href="/usuarios" class="btn">Cancelar</a>
        </div>

    </form>

    <script type="text/javascript">
        $('#usuario').validate({
            rules: {
                nome: {required: true, minLenght: 2},
                email: {required: true, email: true},
                senha: {required: true},
                confirma: {equalTo: "#senha"},
                role: {required: true}
            }
        });
    </script>  

</div>
