<div>
    <div class="row-fluid">
        <div class="span12">
            <h2><?php echo $this->evento->nome; ?> - <?php echo date("d/m/Y", strtotime($this->evento->realizacao)); ?></h2>
        </div>
    </div>

    <hr>

    <ul class="breadcrumb">
        <li><a href="/">Visão Geral</a> <span class="divider">/</span></li>
        <li><a href="/eventos">Eventos</a> <span class="divider">/</span></li>
        <li><a href="/eventos/detalhes/id/<?php echo $this->evento->id; ?>"><?php echo $this->evento->nome; ?></a> <span class="divider">/</span></li>
        <li><a href="/divulgadores/evento/<?php echo $this->evento->id; ?>">Divulgadores</a> <span class="divider">/</span></li>
        <li class="active">Novo</li>
    </ul>

    <div class="row-fluid">

        <?php include(APPLICATION_PATH . '/views/scripts/partials/menu-evento.phtml'); ?>

        <div class="span9">
            <div class="row-fluid">
                <h2>Novo Divulgador</h2>

                <hr>

                <form method="post" class="form-horizontal" id="usuario">
                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group">
                                <label class="control-label">
                                    <label for="nome">Nome</label>
                                </label>
                                <div class="controls">
                                    <input type="text" name="nome" class="input-xlarge">							
                                </div>
                                <input type="hidden" name="id_evento" value="<?php echo $this->evento->id; ?>">
                            </div>
                        </div>
                    </div>

                    <div class="form-actions">
                        <input type="submit" id="submitbutton" class="btn btn-primary" value="Salvar">  
                        <a href="/divulgadores/evento/<?php echo $this->evento->id; ?>" class="btn">Cancelar</a>
                    </div>

                </form>

                <script type="text/javascript">
                    $('#usuario').validate({
                        rules: {
                            nome: {required: true, minLenght: 2}
                        }
                    });
                </script>  

            </div>

        </div>
    </div>
</div>