<div>
    <div class="row-fluid">
        <div class="span12">
            <h2><?php echo $this->evento->nome; ?> - <?php echo date("d/m/Y", strtotime($this->evento->realizacao)); ?></h2>
        </div>
    </div>

    <hr>

    <ul class="breadcrumb">
        <li><a href="/">Visão Geral</a> <span class="divider">/</span></li>
        <li><a href="/eventos">Eventos</a> <span class="divider">/</span></li>
        <li><a href="/eventos/detalhes/id/<?php echo $this->evento->id; ?>"><?php echo $this->evento->nome; ?></a> <span class="divider">/</span></li>
        <li><a href="/Inscrições/evento/<?php echo $this->evento->id; ?>">Inscrições</a> <span class="divider">/</span></li>
        <li class="active">Editar</li>
    </ul>

    <div class="row-fluid">

        <?php include(APPLICATION_PATH . '/views/scripts/partials/menu-evento.phtml'); ?>

        <div class="span9">
            <div class="row-fluid">
                <h2>Editar Inscrição</h2>

                <hr>

                <form method="post" class="form-horizontal" id="usuario">
                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group">
                                <label class="control-label">
                                    <label for="nome">Nome</label>
                                </label>
                                <div class="controls">
                                    <input type="text" name="nome" class="input-xlarge" value="<?php echo $this->inscricao->nome; ?>">							
                                </div>
                                <input type="hidden" name="id_evento" value="<?php echo $this->evento->id; ?>">
                            </div>

                            <div class="control-group">
                                <label class="control-label">
                                    <label for="cpf">CPF</label>
                                </label>
                                <div class="controls">
                                    <input type="text" name="cpf" class="input-xlarge cpf" value="<?php echo $this->inscricao->cpf; ?>">							
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">
                                    <label for="rg">RG</label>
                                </label>
                                <div class="controls">
                                    <input type="text" name="rg" class="input-xlarge rg" value="<?php echo $this->inscricao->rg; ?>">							
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">
                                    <label for="telefone">Telefone</label>
                                </label>
                                <div class="controls">
                                    <input type="text" name="telefone" class="input-xlarge fone" value="<?php echo $this->inscricao->telefone; ?>">							
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">
                                    <label for="email">E-mail</label>
                                </label>
                                <div class="controls">
                                    <input type="text" name="email" class="input-xlarge" value="<?php echo $this->inscricao->email; ?>">							
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">
                                    <label for="divulgador">Divulgador Responsável</label>
                                </label>
                                <div class="controls">
                                    <select name="id_divulgador" id="divulgador" class="input-xlarge">
                                        <option value="">Selecione um Divulgador....</option>
                                        <?php foreach ($this->divulgadores as $divulgador) : ?>
                                            <?php $selected = ($divulgador->id == $this->inscricao->id_divulgador ? 'selected="selected"' : ''); ?>
                                            <option <?php echo $selected; ?> value="<?php echo $divulgador->id; ?>"><?php echo $divulgador->nome; ?></option>
                                        <?php endforeach; ?>
                                    </select>							
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-actions">
                        <input type="submit" id="submitbutton" class="btn btn-primary" value="Salvar">  
                        <a href="/inscricoes/evento/<?php echo $this->evento->id; ?>" class="btn">Cancelar</a>
                    </div>

                </form>

                <script type="text/javascript">
                    $('#usuario').validate({
                        rules: {
                            nome: {required: true, minLenght: 2},
                            email: {email: true},
                            id_divulgador: {required: true}
                        }
                    });
                </script>  

            </div>

        </div>
    </div>
</div>