<div>
    <div class="row-fluid">
        <div class="span12">
            <h2><?php echo $this->evento->nome; ?> - <?php echo date("d/m/Y", strtotime($this->evento->realizacao)); ?></h2>
        </div>
    </div>

    <hr>

    <ul class="breadcrumb">
        <li><a href="/">Visão Geral</a> <span class="divider">/</span></li>
        <li><a href="/eventos">Eventos</a> <span class="divider">/</span></li>
        <li><a href="/eventos/detalhes/id/<?php echo $this->evento->id; ?>"><?php echo $this->evento->nome; ?></a> <span class="divider">/</span></li>
        <li class="active">Inscrições</li>
    </ul>

    <div class="row-fluid">

        <?php include(APPLICATION_PATH . '/views/scripts/partials/menu-evento.phtml'); ?>

        <div class="span9">
            <p><a href="/inscricoes/novo/evento/<?php echo $this->evento->id; ?>" class="btn btn-primary"><i class="icon-user"></i> &nbsp; Nova Inscrição</a></p>

            <table class="table table-hover dataTable">
                <thead>
                    <tr>
                        <th width="5%">#id</th>
                        <th>Nome</th>
                        <th>Telefone</th>
                        <th>Divulgador</th>
                        <th>Situação</th>
                        <th width="17%">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->inscricoes as $inscricao) : ?>
                        <tr>
                            <td><?php echo $inscricao->id; ?></td>
                            <td><?php echo $inscricao->nome; ?></td>
                            <td><?php echo $inscricao->telefone; ?></td>
                            <td><?php echo $inscricao->getDivulgador()->nome; ?></td>
                            <td>
                                <?php echo ($inscricao->getSituacao() == 'Pendente' ? '<span class="badge badge-important">Pendente</span>' : '<span class="badge badge-success">Confirmado</span>'); ?>
                            </td>
                            <td>
                                <?php if ($inscricao->getSituacao() == 'Pendente'): ?>
                                    <a href="/inscricoes/confirmar/id/<?php echo $inscricao->id; ?>/evento/<?php echo $this->evento->id; ?>" class="btn btn-small btn-success"><i class="icon-arrow-up" title="Confirmar Pagamento"></i></a>
                                <?php endif; ?>

                                <?php if ($inscricao->getSituacao() == 'Pago'): ?>
                                    <a href="/inscricoes/estornar/id/<?php echo $inscricao->id; ?>/evento/<?php echo $this->evento->id; ?>" class="btn btn-small btn-warning"><i class="icon-arrow-down" title="Estornar Pagamento"></i></a>
                                <?php endif; ?>

                                <a href="/inscricoes/editar/id/<?php echo $inscricao->id; ?>/evento/<?php echo $this->evento->id; ?>" class="btn btn-small"><i class="icon-edit" title="Editar Inscrição"></i></a>
                                <a href="/inscricoes/remover/id/<?php echo $inscricao->id; ?>/evento/<?php echo $this->evento->id; ?>" class="btn btn-danger btn-small delete" title="Remover Inscrição"><i class="icon-remove-sign"></i></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <script type="text/javascript">
                $(function() {
                    var oTable = $('.dataTable').dataTable({
                        "sPaginationType": "full_numbers",
                        "sDom": 'f<"toolbar">lrtip',
                        "oLanguage": {
                            "sProcessing": "Processando...",
                            "sLengthMenu": "Mostrar _MENU_ registros",
                            "sZeroRecords": "Não foram encontrados resultados",
                            "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                            "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
                            "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                            "sInfoPostFix": "",
                            "sSearch": "Buscar:",
                            "sUrl": "",
                            "oPaginate": {
                                "sFirst": "Primeiro",
                                "sPrevious": "Anterior",
                                "sNext": "Seguinte",
                                "sLast": "Último"
                            }
                        }
                    });
                });
            </script> 
        </div>
    </div>
</div>